title: Alberto Vera, MBA
logo: /assets/img/headshot_circle.png
description: Al is very detail oriented analytical thinker who posses a B.S. in Finance, a M.S. in Sports Technology, and a MBA with a concentration in Analytics
show_downloads: true
theme: jekyll-theme-minimal
